### PR TITLE
ENH support extra extension names

### PR DESCRIPTION
**Pull request by beckermr**
This PR adds support for reading extra extensions with the same geometry as the image extension.

### CODE REVIEW

**Comment by beckermr** [comment]
@esheldon I could use some review here.

**Comment by esheldon** [comment]
that looks like an improvement. Should we add a test?  We could pull the "_fakemeds.py" from ngmix

**Comment by beckermr** [comment]
I'd like to defer tests to another PR due to time. Is that ok?

**Comment by esheldon** [comment]
OK

**Pull request merged**
