### PR TITLE
ENH allow variable number of jobs for joblib

### PR DESCRIPTION
**Pull request by beckermr**
Adds a config key `max_joblib_workers` for controlling the number of jobs.

### CODE REVIEW

**Comment by esheldon** [comment]
```
Traceback (most recent call last):
  File "/gpfs01/astro/workarea/esheldon/anaconda-dirs/miniconda3/envs/medstest/bin/desmeds-make-meds-desdm", line 36, in <module>
    main()
  File "/gpfs01/astro/workarea/esheldon/anaconda-dirs/miniconda3/envs/medstest/bin/desmeds-make-meds-desdm", line 34, in main
    maker.go()
  File "/gpfs01/astro/workarea/esheldon/anaconda-dirs/miniconda3/envs/medstest/lib/python3.8/site-packages/desmeds/desdm_maker.py", line 113, in go
    maker.write(fname)
  File "/gpfs01/astro/workarea/esheldon/anaconda-dirs/miniconda3/envs/medstest/lib/python3.8/site-packages/meds/maker.py", line 98, in write
    self._build_meds_layout()
  File "/gpfs01/astro/workarea/esheldon/anaconda-dirs/miniconda3/envs/medstest/lib/python3.8/site-packages/meds/maker.py", line 619, in _build_meds_layout
    self._get_pos_and_bounds(self.obj_data, file_id)
  File "/gpfs01/astro/workarea/esheldon/anaconda-dirs/miniconda3/envs/medstest/lib/python3.8/site-packages/meds/maker.py", line 733, in _get_pos_and_bounds
    pos = self._do_sky2image(
  File "/gpfs01/astro/workarea/esheldon/anaconda-dirs/miniconda3/envs/medstest/lib/python3.8/site-packages/meds/maker.py", line 929, in _do_sky2image
    with joblib.parallel_backend("multiprocessing", inner_max_num_threads=1):
  File "/gpfs01/astro/workarea/esheldon/anaconda-dirs/miniconda3/envs/medstest/lib/python3.8/site-packages/joblib/parallel.py", line 191, in __init__
    assert backend.supports_inner_max_num_threads, msg
AssertionError: MultiprocessingBackend does not accept setting the inner_max_num_threads argument.

```

**Comment by beckermr** [comment]
Ohhhh frack. 🤦‍♂

**Comment by beckermr** [comment]
I guess we need to set OMP_NUM_THREADS on the outside.

**Comment by beckermr** [comment]
we could also let people set the backend to loky - this was only an issue when running inside an MPI process - I don't think DESDM is using MPI on the outside.

**Comment by esheldon** [comment]
they do not currently

**Comment by esheldon** [comment]
I did a quick test and loky works

**Comment by esheldon** [comment]
look ok to you?

**Comment by beckermr** [comment]
We cannot use loky since this will break the DES sims pipeline.

**Comment by beckermr** [comment]
I will add an option to the config.

**Comment by esheldon** [comment]
ok, feel free to do what you need to

**Comment by beckermr** [comment]
OK. the config should now be a top-level joblib section with keys

```yaml
joblib:
   backend: 'loky'
   max_workers: 10
```

**Comment by esheldon** [comment]
works for me

**Comment by esheldon** [comment]
I'm running a full test of the meds maker to ensure it works end to end.  If all is ok I'll merge

**Comment by esheldon** [comment]
test ran fine

**Pull request merged**
