### PR TITLE
PSF performance

### PR DESCRIPTION
**Pull request by beckermr**
This PR adds some performance enhancements for making MEDS files with PSFs.

### CODE REVIEW

**Comment by esheldon** [comment]
I worry about writing to a file in parallel like this.

I have other concerns as well, but let's discuss that first

**Comment by beckermr** [comment]
The writing never happens in parallel.

**Comment by esheldon** [comment]
this is in _write_psf_cutouts

https://github.com/esheldon/meds/pull/34/commits/0f97df79bd2e76673c81dced2f563f69f9bb7b08

**Comment by esheldon** [comment]
its hard to see the total context

**Comment by beckermr** [comment]
I'll add comments.

**Comment by esheldon** [comment]
My main request is to refactor _write_psf_cutouts and other codes so they isn't so long.  When joblib is to be used, call to a second method `_write_psf_cutouts_parallel` or something

**Comment by beckermr** [comment]
Will do!

**Comment by beckermr** [comment]
I didn't split up the joblib code because it is all highly coupled.

**Comment by esheldon** [comment]
Yeah, but everything in the block after `if self.get('use_joblib', False):` could be moved to a method

**Comment by beckermr** [comment]
done.

**Comment by beckermr** [comment]
This PR is ready to go. When using the joblib option, the code caches the PSF images to temp disk to save on memory usage. Shall we merge @esheldon ?

**Pull request merged**
